### PR TITLE
respect PEP8 coding style

### PR DESCRIPTION
**Pull request by jakubjedelsky**
No new functions, just coding edit coding style to pass with pep8 check. Except `E501 line too long`.

### CODE REVIEW

**Comment by sickill** [comment]
Thanks Jakub!

**Comment by sickill** [comment]
Hmm, looks like this change is not compatible with #179.

**Comment by sickill** [comment]
Moving this setuptools import to the top is an option, but it will result in "no setuptools found" error for people on Python 2, unless they have setuptools installed.

Another option would be to exclude `setup.py` from pep8 checks.

**Comment by jakubjedelsky** [comment]
I'll check it in a free time today. Maybe it will be fine to have `setuptools` as a requirement for instalation. Anyway, `setuptools` is so widespread that almost everyone have to have it installed :)

**Comment by sickill** [comment]
I'm gonna fully trust you on this as I have little experience with Python's packaging specifics and current state of Python ecosystem 😛

**Pull request merged**
