### PR TITLE
djds/annotate

### PR DESCRIPTION
**Pull request by djds**
- [style] Format package code
- [ci] Format asciinema workflow; add Python 3.10
- [container] Update Dockerfile for PEP 518 build
- [ci] Run container integration tests to CI
- [style] Ignore line break before binary operator
- [style] Replace calls to format() with f-strings
- Rename asciinema/pty.py => pty_.py
- [typing] Annotate asciinema.asciicast
- [typing] Annotate asciinema.async_worker
- [build] Refactor Makefile
- [build] Add clean, clean.all targets to Makefile
- [build] Run build target in VIRTUAL_ENV
- [build] Remove .mypy_cache with clean.all Makefile target
- [test] Convert unittests runner nose => pytest
- [test] Update test for asciinema.pty_
- [typing] Annotate ascinnema.urllib_http_adapter
- [typing] Annotate asciinema.api
- [typing] Annotate asciinema.config
- [typing] Annotate asciinema.term
- [typing] Annotate asciinema.pty_
- [typing] Annotate asciinema.__main__
- [typing] Annotate asciinema.player
- [typing] Annotate asciinema.recorder
- Refactor asciinema.notifier
- [typing] Annotate asciinema.commands.auth
- [typing] Annotate asciinema.commands.upload
- [typing] Annotate asciinema.commands.record
- [typing] Annotate asciinema.__init__
- [typing] Annotate asciinema.commands.cat
- [typing] Annotate asciinema.commands.command
- [typing] Annotate asciinema.commands.play
- [typing] Add asciinema/py.typed
- Support Python 3.6; remove annotations from __future__
- v2.2.0: Require Python 3.6+
- Normalize user-agent header casing in asciinema.api
- [doc] Update README

### CODE REVIEW

**Comment by sickill** [comment]
I see the split PRs are drafts. Do you plan to work on them more or they're ready from your POV?

**Comment by djds** [comment]
@sickill yes I want to make sure to resolve all conflicts between the three separated PRs before submitting them for review. Given the extensive changes, in splitting these out I think there's a chance of duplicate commits so that they merge cleanly on top of `asciinema:develop`. The original (massive) MR may be actually easier to review due to the fact that the individual commits should still be mostly atomic. Let me know what you think.

**Comment by sickill** [comment]
@djds Yeah, I'm reviewing #445 as a whole. Reading individual comments, one after another, like a story. So far so good 👍

**Comment by sickill** [comment]
Closing this as we'll just go with the all-in-one #445.

**Pull request closed without merging**
