### PR TITLE
asciinema 2.0

### PR DESCRIPTION
**Pull request by sickill**
Highlights:

- recording and playback of new asciicast v2 format - #196 #227 #228
  - draft of v2 format spec: https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md
  - writing to disk in real-time, preventing losing sessions on crashes/reboots 
  - enabling recording and playing of very long asciicasts without involving lots of RAM
- (optional) stdin recording in order to display keys pressed overlay in web player
- storing current terminal color theme in the recording - #221 #233 (specific technique to be figured out, see #11)
- ability to capture extra environment variables - #222 #230
- saving timestamp of recording session - #229

See [2.0 milestone](https://github.com/asciinema/asciinema/milestone/5) for all the things we plan to include.

### CODE REVIEW

**Comment by SeriousM** [comment]
The recent commits smell like gold plating! Is the release near?

**Comment by sickill** [comment]
@SeriousM very near. I don't have anything major to add to 2.0, probably only documentation tweaks. Now, would be really awesome if someone could give it a ride, testing the new shiny commands and options. Could you try the latest version from `develop` branch?

**Comment by KurtPfeifle** [comment]
@sickill wrote further above:

> *"Now, would be really awesome if someone could give it a ride"*

I'm about to record a few little tutorials (to publish on asciinema.org as well). I'll give the develop branch a workout with it. But two questions first:

1. Will asciinema.org be able to re-play the v2 already? Or will that have to wait?
1. Is there a way to convert v2 format to v1?

**Comment by sickill** [comment]
@KurtPfeifle asciinema.org supports v2 already, both the API endpoint and the player version there.

As for converting v2 -> v1, it would be trivial to write a converter script, as it would be mostly about shoving event stream into the header and serializing it as single JSON object.

I'm curious, what's the use case for doing v2 -> v1? I'd rather see people converting v1 -> v2, as it has many benefits over v1.

**Comment by KurtPfeifle** [comment]
@sickill:
I do not have any real use case for v2 -> v1 conversion. I asked just in case... in case I finally had a good v2 recording I like, but asciiinema.org could not replay it from the web. So given your statement about asciinema.org supporting v2 already, I'm happy.

**Comment by KurtPfeifle** [comment]
@sickill:
Ha!, I can now think of a use case for v2 -> v1 conversion: I'd like to edit the cast file after it is done. v2 makes it definitely more difficult to do so -- v1 is much easier (for me, at least).

**Comment by sickill** [comment]
What specifically makes editing v1 easier than v2 for you?

**Comment by KurtPfeifle** [comment]
@sickill asked above:

> *"What specifically makes editing v1 easier than v2 for you?"*

I was completely wrong, sorry. Had been looking at the wrong examples...

Meanwhile I generated a few short v2 files myself, and it should be fine!

**Comment by SeriousM** [comment]
Woohoo! Congratulations for the 2.0.0 merge!

**Pull request merged**
