### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by mattn**
channel2

### CODE REVIEW

**Comment by mattn** [comment]
Sorry, some of dependencies are entried as code.google.com/p/. AFAIK, it's gone. So I can't update Godep.json.

**Comment by sickill** [comment]
I don't have a Windows box ready to test it at the moment, but will get one soon.

Anyway, I don't see any Windows specific PTY recording code. Does `kr/pty` package just work on Windows console??

**Comment by mattn** [comment]
Ah, sorry, I forgot to add file. I will add soon.

> Does kr/pty package just work on Windows console??

No. it doesn't.

**Comment by mattn** [comment]
done.

**Comment by sickill** [comment]
Hey @mattn. This is hell of a PR :)

Looks like you put a lot of effort into emulating PTY under Windows. There's a lot going on in this code.
I suspected that there's no way to get a real PTY and real ANSI escape codes on Windows and the only way is to "scrape" the terminal buffer in regular interval.

I'm not a Windows user and I don't often have access to Windows so it would be very hard for me to maintain this (making sure all is okay, releasing .exe). Because of this and the fact it hasn't been widely tested yet, I'm hesitant to merge it at this point. I expect some inconsistency with ANSI codes, also scraping terminal buffer every 10ms is potentially CPU intensive (but I understand we don't know a better way!).

However, I really appreciate the work you have put in this. I'd be very happy to point people wanting to record on Windows to your fork. I can link to it from the README and also from asciinema.org docs. You could then maintain it at your own pace there, as a semi-official Windows fork.

What do you say?

**Comment by mattn** [comment]
I don't mind that suggestion. Do it your best. :+1:

**Comment by sickill** [comment]
Btw, I heard someone was able to run original asciinema on Windows 10 recently (thanks to bash/linux layer included in Windows).

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/issues/292

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/issues/136

**Comment by svnpenn** [comment]
https://github.com/asciinema/asciinema/issues/47

**Comment by haraldreingruber** [comment]
I nice workaround is installing Asciinema via WSL, start a recording session form WSL Bash and then open a CMD session via `cmd.exe`. 

It's a bit less convenient than being able to record from CMD directly but form an output perspective the only disadvantage is that the initial `cmd.exe` call is also recorded, and would need to be removed in a post-processing step in order to avoid confusion. Maybe somebody knows a trick to delay the recording so that capturing is started after calling `cmd.exe`?

**Comment by rollingmoai** [comment]
This port for Windows works great: https://github.com/Watfaq/PowerSession-rs

**Pull request closed without merging**
