### PR TITLE
Add playback controls

### PR DESCRIPTION
**Pull request by cactorium**
Resolves https://github.com/asciinema/asciinema/issues/133 , but using some different controls because it's simpler to implement.

- '-' slows down 2x
- '+' speeds up 2x
- space pauses the playback
- period steps forward one terminal change

This was fairly simple so I'm guessing I'm missing some reasons why this wasn't implemented earlier, so please lemme know what changes need to be made!

### CODE REVIEW

**Comment by cactorium** [comment]
Finally figured out how to actually pass the style linter, it turns out vim's pymode doesn't quite cover the same stuff as pep8

**Comment by davidvossel** [comment]
The pause functionality works great for me. I'm actually going to use this in a presentation next week. Thanks!

**Comment by sickill** [comment]
Thanks for the PR @cactorium. I appreciate the work you put into this, however I won't be able to merge this now.

First and foremost, if you read [our contribution guidelines](https://github.com/asciinema/asciinema/blob/master/CONTRIBUTING.md#proposing-featureschanges-pull-requests) (which is also linked/mentioned during PR creation) you would notice we prefer to discuss any new features before implementing them. This way we can save time of contributors and maintainers, by pointing contributors to alternative/existing solutions, simplify approach etc etc. This also allows us to accept (and later maintain) features that make sense to most of asciinema users.

The other thing is we're working on asciinema 2.0 on `v2` branch (also see [2.0 milestone](https://github.com/asciinema/asciinema/milestone/5)). There are many changes there, and this PR won't likely merge there.

We are yet to see if we'd like this particular feature to be part of 2.0, or maybe 2.1. In general, asciinema's main mission is to smoothly record and share on the web, so in-terminal playback is nice, but not essential. However I still think this might be a useful addition, so I'm open to having a separate GH issue to discuss this.

**Comment by ferdonline** [comment]
Guys, I believe this is a nice little contribution, why not spending 5min to review and incorporate? That's the open source spirit no?

**Comment by cactorium** [comment]
To be honest, I'm not up for spending what sounds like weeks or months of
discussion to maybe to land a 22 line change. If you or anyone else is
interested, go for it :)! Afaict this'd merge almost perfectly fine on the
v2 branch, you'd just need to fork off my branch, rebase off of v2, and add
in a little bit of code to use the local variable stdout instead of
asciinema.stdout()

**Comment by ferdonline** [comment]
For what is worth I forked your repo and merged this PR branch in the develop branch.
It is working fine for me. Feel free to check it out.

**Comment by sickill** [comment]
@ferdonline I really don't like that you're doing this "open source spirit" guilt trip as a way to force this PR to be merged.

I didn't say we don't want this functionality, and I explained why it wasn't merged at this point. I'm pretty sure you are not the one who would later maintain this functionality. Like most open source maintainers I'm working on asciinema in my free time and it happens more often than not that people submit new features which *I myself* later have to maintain, because they simply move on. Doesn't matter whether it's 22 lines change or 220. Sorry for not being this "accept-all-the-PRs" guy, but I don't think rage-forking is a good definition of "open source spirit" either.

**Comment by cactorium** [comment]
Sorry if any of that ill will is my fault. I understand the burdens
involved with maintaining code, which is why I was and am totally willing
to leave this PR closed. My instructions were meant for setting up and the
testing this code on the right branch in case anyone else wants to try to
work on this feature, not for trying to start a fork of the project

**Comment by sickill** [comment]
So I took a stab at this again. @cactorium's patch required some major changes to work with current develop branch, but we have it now: https://github.com/asciinema/asciinema/commit/fb1e25d933851743f4aed744279ab5361af9ad4b. Thanks Kelvin for the original implementation! (I looked for a way to set multiple authors on git commit but it seems there can be only one author, so you're credited in the commit message)

**Comment by cactorium** [comment]
I'm glad you guys managed to add it in!

**Pull request closed without merging**
