### PR TITLE
Fix **write(2)** to pty master fd synchronously causing deadlock

### PR DESCRIPTION
**Pull request by Low-power**
**asciinema(1)** currently **write(2)**s to pty master fd synchronously, which could be blocking if the internal pty input buffer became full; while the programs running under the pty may also be blocking on writing to pty slave fd, because the pty output buffer can also become full at same time. Once this happens, the entire terminal session hangs; the only way to get rid of it is to kill the asciinema processes via `SIGKILL`.

The following steps can be used to reproduce the bug:

* Start a terminal recording
* Run `cat` in the pseudo terminal that's being recorded
* Prepare large amount of text and put it in X11 primary selection (or clipboard if that's preferred); how about 2000 lines of `w` repeating 80 times for each line?
```sh
i=0; while [ $i -lt 2000 ]; do echo wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww; i=$((i+1)); done | xclip -verbose -selection primary -in -target text/plain
```
* Paste the text into terminal that you previously runs **cat(1)** in
* **asciinema(1)** will likely be hanging at this time

The fix is to use **select(2)** in function `copy` to check whether the pty master fd is immediately writable, before trying to **write(2)** anything to it.

### CODE REVIEW

**Comment by Low-power** [comment]
## Some **truss(1)** logs showing the deadlock

**truss(1)** output for **asciinema(1)** process that's handing pseudo terminal I/O:
```
30904: write(4,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,1024) = 1024 (0x400)
30904: _umtx_op(0x806e14014,UMTX_OP_SEM2_WAKE,0x0,0x0,0x0) = 0 (0x0)
30904: _umtx_op(0x806e14014,UMTX_OP_SEM2_WAIT,0x0,0x0,0x0) = 0 (0x0)
30904: _umtx_op(0x801e162b8,UMTX_OP_NWAKE_PRIVATE,0x1,0x0,0x0) = 0 (0x0)
30904: _umtx_op(0x8007f5008,UMTX_OP_WAIT_UINT_PRIVATE,0x0,0x18,0x7fffdfffd0e8) = 0 (0x0)
30904: write(9,"\0\0\^D \M^@\^C]q\0(G@\\\M-@\M-'"...,1060) = 1060 (0x424)
30904: read(0,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,1024) = 1024 (0x400)
30904: write(11,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,1024) = 768 (0x300)
30904: SIGNAL 9 (SIGKILL)
```

**truss(1)** output for **cat(1)** process:
```
31743: read(0,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,4096) = 81 (0x51)
31743: write(1,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,81) = 81 (0x51)
31743: read(0,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,4096) = 81 (0x51)
31743: write(1,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,81) = 81 (0x51)
31743: read(0,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,4096) = 81 (0x51)
31743: write(1,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,81) = 81 (0x51)
31743: read(0,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,4096) = 81 (0x51)
31743: write(1,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"...,81) = 1 (0x1)
31743: SIGNAL 9 (SIGKILL)
31743: process killed, signal = 9
```

As from these outputs, the last **write(2)** call hangs in both processes, until they received `SIGKILL`.

**Comment by sickill** [comment]
Great, this problem is actually something we debugged recently in https://github.com/kovidgoyal/kitty/issues/6272 and we have open issue for https://github.com/asciinema/asciinema/issues/549

I'll take a look at your patch shortly. Thanks!

**Comment by AkechiShiro** [comment]
@sickill When you get time to look at the patch in depth, could you let me know if this patch could fix the bug report I created ?

**Comment by sickill** [comment]
Made a small fix to this https://github.com/asciinema/asciinema/commit/1514591628f6d121fb886ce2f5073336f8c466e8

**Comment by sickill** [comment]
@AkechiShiro I tested on your bug repro instructions and it seems the patch fixes it indeed :tada:

**Comment by sickill** [comment]
I'll release new version shortly.

**Comment by AkechiShiro** [comment]
Thanks a lot !! @sickill @Low-power

**Comment by AkechiShiro** [comment]
@sickill all the others terminal recorders must be affected by this race condition as well, I don't know if this bug should be reported to them as well, I'll let you handle that, as my issue is finally fixed.
Will give it a try when a new release is made of asciinema

**Comment by sickill** [comment]
@AkechiShiro just released 2.3.0: https://pypi.org/project/asciinema/2.3.0/

**Pull request merged**
